version: 2.1

commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      # Add parameter here   
      
      workflow_id:
        type: string
      event:
        type: string
      
    steps:
      - run:
          name: Destroy environments << parameters.workflow_id >>
          when: on_fail
          command: |
            # Your code here
            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.id >>